import os
import re
import sqlite3
from datetime import date
from pathlib import Path

from flask import current_app, g
from werkzeug.security import generate_password_hash

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # Local SQLite mode does not need psycopg installed.
    psycopg = None
    dict_row = None


SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    role TEXT NOT NULL CHECK (role IN ('admin', 'faculty', 'student')),
    profile_picture TEXT,
    institution_type TEXT,
    institution_name TEXT,
    class_roll_number TEXT,
    roll_number TEXT UNIQUE,
    registration_number TEXT UNIQUE,
    full_name TEXT NOT NULL,
    father_name TEXT,
    branch TEXT,
    semester TEXT,
    year TEXT,
    dob TEXT,
    mobile_number TEXT,
    gmail TEXT,
    email TEXT,
    password_hash TEXT NOT NULL,
    is_mobile_verified INTEGER NOT NULL DEFAULT 0,
    created_by INTEGER,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS otp_codes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    mobile_number TEXT NOT NULL,
    otp_code TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    is_used INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attendance (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id INTEGER NOT NULL,
    attendance_date TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Present', 'Absent', 'Late', 'Leave')),
    marked_by INTEGER NOT NULL,
    remarks TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(student_id, attendance_date),
    FOREIGN KEY(student_id) REFERENCES users(id),
    FOREIGN KEY(marked_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS pending_changes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    target_user_id INTEGER NOT NULL,
    target_role TEXT NOT NULL CHECK (target_role IN ('faculty', 'student')),
    requested_by INTEGER NOT NULL,
    approver_role TEXT NOT NULL CHECK (approver_role IN ('admin', 'faculty')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    payload TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TEXT,
    FOREIGN KEY(target_user_id) REFERENCES users(id),
    FOREIGN KEY(requested_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS student_applications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id INTEGER NOT NULL,
    application_date TEXT NOT NULL,
    start_date TEXT,
    end_date TEXT,
    reason TEXT NOT NULL,
    file_name TEXT,
    original_file_name TEXT,
    file_type TEXT,
    status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'approved', 'rejected')),
    resolved_by INTEGER,
    resolved_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(student_id) REFERENCES users(id),
    FOREIGN KEY(resolved_by) REFERENCES users(id)
);
"""


POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role TEXT NOT NULL CHECK (role IN ('admin', 'faculty', 'student')),
    profile_picture TEXT,
    institution_type TEXT,
    institution_name TEXT,
    class_roll_number TEXT,
    roll_number TEXT UNIQUE,
    registration_number TEXT UNIQUE,
    full_name TEXT NOT NULL,
    father_name TEXT,
    branch TEXT,
    semester TEXT,
    year TEXT,
    dob TEXT,
    mobile_number TEXT,
    gmail TEXT,
    email TEXT,
    password_hash TEXT NOT NULL,
    is_mobile_verified INTEGER NOT NULL DEFAULT 0,
    created_by INTEGER REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS otp_codes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mobile_number TEXT NOT NULL,
    otp_code TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    is_used INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attendance (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES users(id),
    attendance_date TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Present', 'Absent', 'Late', 'Leave')),
    marked_by INTEGER NOT NULL REFERENCES users(id),
    remarks TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(student_id, attendance_date)
);

CREATE TABLE IF NOT EXISTS pending_changes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_user_id INTEGER NOT NULL REFERENCES users(id),
    target_role TEXT NOT NULL CHECK (target_role IN ('faculty', 'student')),
    requested_by INTEGER NOT NULL REFERENCES users(id),
    approver_role TEXT NOT NULL CHECK (approver_role IN ('admin', 'faculty')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    payload TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS student_applications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES users(id),
    application_date TEXT NOT NULL,
    start_date TEXT,
    end_date TEXT,
    reason TEXT NOT NULL,
    file_name TEXT,
    original_file_name TEXT,
    file_type TEXT,
    status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'approved', 'rejected')),
    resolved_by INTEGER REFERENCES users(id),
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""


POSTGRES_COLUMNS = {
    "users": {
        "profile_picture": "TEXT",
        "institution_type": "TEXT",
        "institution_name": "TEXT",
        "class_roll_number": "TEXT",
        "mobile_number": "TEXT",
    },
    "student_applications": {
        "start_date": "TEXT",
        "end_date": "TEXT",
        "resolved_by": "INTEGER REFERENCES users(id)",
        "resolved_at": "TIMESTAMPTZ",
    },
}


def postgres_url():
    return (
        current_app.config.get("SUPABASE_DB_URL")
        or current_app.config.get("DATABASE_URL")
        or os.environ.get("SUPABASE_DB_URL")
        or os.environ.get("DATABASE_URL")
        or ""
    ).strip()


def using_postgres():
    url = postgres_url()
    return url.startswith("postgres://") or url.startswith("postgresql://")


def _convert_qmark(sql):
    parts = sql.split("'")
    for index in range(0, len(parts), 2):
        parts[index] = parts[index].replace("?", "%s")
    return "'".join(parts)


def _convert_named(sql):
    return re.sub(r":([A-Za-z_][A-Za-z0-9_]*)", r"%(\1)s", sql)


def _escape_literal_percent(sql):
    protected = {}

    def protect(match):
        token = f"__PG_PLACEHOLDER_{len(protected)}__"
        protected[token] = match.group(0)
        return token

    sql = re.sub(r"%\([A-Za-z_][A-Za-z0-9_]*\)s|%s", protect, sql)
    sql = sql.replace("%", "%%")
    for token, placeholder in protected.items():
        sql = sql.replace(token, placeholder)
    return sql


def _convert_sql_for_postgres(sql):
    sql = _convert_qmark(sql)
    sql = _convert_named(sql)
    sql = sql.replace("GLOB '[0-9]*'", "~ '^[0-9]+$'")
    return _escape_literal_percent(sql)


class PostgresConnection:
    def __init__(self, url):
        self._conn = psycopg.connect(url, row_factory=dict_row)

    def execute(self, sql, params=None):
        converted_sql = _convert_sql_for_postgres(sql)
        return self._conn.execute(converted_sql, params or ())

    def executescript(self, script):
        for statement in script.split(";"):
            statement = statement.strip()
            if statement:
                self.execute(statement)

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()


def get_db():
    if "db" not in g:
        if using_postgres():
            if psycopg is None:
                raise RuntimeError("psycopg is required when DATABASE_URL or SUPABASE_DB_URL is set.")
            g.db = PostgresConnection(postgres_url())
        else:
            db_path = Path(current_app.root_path).parent / current_app.config["DATABASE"]
            g.db = sqlite3.connect(db_path)
            g.db.row_factory = sqlite3.Row
    return g.db


def close_db(_=None):
    db = g.pop("db", None)
    if db is not None:
        db.close()


def init_db():
    db = get_db()
    if using_postgres():
        db.executescript(POSTGRES_SCHEMA)
        migrate_postgres(db)
    else:
        db.executescript(SQLITE_SCHEMA)
        migrate_sqlite(db)
    ensure_default_admin(db)
    db.commit()


def migrate_postgres(db):
    for table_name, columns in POSTGRES_COLUMNS.items():
        existing_columns = {
            row["column_name"]
            for row in db.execute(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name = ?
                """,
                (table_name,),
            ).fetchall()
        }
        for column_name, definition in columns.items():
            if column_name not in existing_columns:
                db.execute(f"ALTER TABLE {table_name} ADD COLUMN {column_name} {definition}")

    db.execute(
        """
        UPDATE attendance
        SET status = 'Leave',
            remarks = REPLACE(remarks, 'Approved application:', 'Approved leave application:')
        WHERE remarks LIKE 'Approved application:%'
        """
    )


def migrate_sqlite(db):
    user_columns = {
        row["name"] for row in db.execute("PRAGMA table_info(users)").fetchall()
    }
    if "institution_type" not in user_columns:
        db.execute("ALTER TABLE users ADD COLUMN institution_type TEXT")
    if "institution_name" not in user_columns:
        db.execute("ALTER TABLE users ADD COLUMN institution_name TEXT")
    if "class_roll_number" not in user_columns:
        db.execute("ALTER TABLE users ADD COLUMN class_roll_number TEXT")
    if "profile_picture" not in user_columns:
        db.execute("ALTER TABLE users ADD COLUMN profile_picture TEXT")

    users_schema = db.execute(
        "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = 'users'"
    ).fetchone()
    users_sql = users_schema["sql"] if users_schema else ""
    if "mobile_number TEXT UNIQUE" in users_sql:
        db.execute("PRAGMA foreign_keys = OFF")
        db.execute(
            """
            CREATE TABLE users_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                role TEXT NOT NULL CHECK (role IN ('admin', 'faculty', 'student')),
                profile_picture TEXT,
                institution_type TEXT,
                institution_name TEXT,
                class_roll_number TEXT,
                roll_number TEXT UNIQUE,
                registration_number TEXT UNIQUE,
                full_name TEXT NOT NULL,
                father_name TEXT,
                branch TEXT,
                semester TEXT,
                year TEXT,
                dob TEXT,
                mobile_number TEXT,
                gmail TEXT,
                email TEXT,
                password_hash TEXT NOT NULL,
                is_mobile_verified INTEGER NOT NULL DEFAULT 0,
                created_by INTEGER,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY(created_by) REFERENCES users(id)
            )
            """
        )
        db.execute(
            """
            INSERT INTO users_new (
                id, role, profile_picture, institution_type, institution_name,
                class_roll_number, roll_number, registration_number, full_name,
                father_name, branch, semester, year, dob, mobile_number, gmail,
                email, password_hash, is_mobile_verified, created_by, created_at
            )
            SELECT
                id, role, profile_picture, institution_type, institution_name,
                class_roll_number, roll_number, registration_number, full_name,
                father_name, branch, semester, year, dob, mobile_number, gmail,
                email, password_hash, is_mobile_verified, created_by, created_at
            FROM users
            """
        )
        db.execute("DROP TABLE users")
        db.execute("ALTER TABLE users_new RENAME TO users")
        db.execute("PRAGMA foreign_keys = ON")

    attendance_schema = db.execute(
        "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = 'attendance'"
    ).fetchone()
    attendance_sql = attendance_schema["sql"] if attendance_schema else ""
    if "Leave" not in attendance_sql:
        db.execute("ALTER TABLE attendance RENAME TO attendance_old")
        db.execute(
            """
            CREATE TABLE attendance (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                student_id INTEGER NOT NULL,
                attendance_date TEXT NOT NULL,
                status TEXT NOT NULL CHECK (status IN ('Present', 'Absent', 'Late', 'Leave')),
                marked_by INTEGER NOT NULL,
                remarks TEXT,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(student_id, attendance_date),
                FOREIGN KEY(student_id) REFERENCES users(id),
                FOREIGN KEY(marked_by) REFERENCES users(id)
            )
            """
        )
        db.execute(
            """
            INSERT INTO attendance (id, student_id, attendance_date, status, marked_by, remarks, created_at)
            SELECT id, student_id, attendance_date, status, marked_by, remarks, created_at
            FROM attendance_old
            """
        )
        db.execute("DROP TABLE attendance_old")
    db.execute(
        """
        UPDATE attendance
        SET status = 'Leave',
            remarks = REPLACE(remarks, 'Approved application:', 'Approved leave application:')
        WHERE remarks LIKE 'Approved application:%'
        """
    )

    application_columns = {
        row["name"] for row in db.execute("PRAGMA table_info(student_applications)").fetchall()
    }
    application_schema = db.execute(
        "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = 'student_applications'"
    ).fetchone()
    schema_sql = application_schema["sql"] if application_schema else ""
    needs_application_rebuild = (
        "reviewed" in schema_sql
        or "approved" not in schema_sql
        or "start_date" not in application_columns
        or "end_date" not in application_columns
        or "resolved_by" not in application_columns
        or "resolved_at" not in application_columns
    )
    if needs_application_rebuild:
        db.execute("ALTER TABLE student_applications RENAME TO student_applications_old")
        db.execute(
            """
            CREATE TABLE student_applications (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                student_id INTEGER NOT NULL,
                application_date TEXT NOT NULL,
                start_date TEXT,
                end_date TEXT,
                reason TEXT NOT NULL,
                file_name TEXT,
                original_file_name TEXT,
                file_type TEXT,
                status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'approved', 'rejected')),
                resolved_by INTEGER,
                resolved_at TEXT,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY(student_id) REFERENCES users(id),
                FOREIGN KEY(resolved_by) REFERENCES users(id)
            )
            """
        )
        old_columns = {
            row["name"] for row in db.execute("PRAGMA table_info(student_applications_old)").fetchall()
        }
        start_expr = "start_date" if "start_date" in old_columns else "application_date"
        end_expr = "end_date" if "end_date" in old_columns else "application_date"
        resolved_by_expr = "resolved_by" if "resolved_by" in old_columns else "NULL"
        resolved_at_expr = "resolved_at" if "resolved_at" in old_columns else "NULL"
        db.execute(
            f"""
            INSERT INTO student_applications (
                id, student_id, application_date, start_date, end_date, reason,
                file_name, original_file_name, file_type, status, resolved_by, resolved_at, created_at
            )
            SELECT
                id,
                student_id,
                application_date,
                COALESCE(NULLIF({start_expr}, ''), application_date),
                COALESCE(NULLIF({end_expr}, ''), application_date),
                reason,
                file_name,
                original_file_name,
                file_type,
                CASE
                    WHEN status = 'reviewed' THEN 'approved'
                    WHEN status IN ('submitted', 'approved', 'rejected') THEN status
                    ELSE 'submitted'
                END,
                {resolved_by_expr},
                {resolved_at_expr},
                created_at
            FROM student_applications_old
            """
        )
        db.execute("DROP TABLE student_applications_old")


def ensure_default_admin(db):
    admin = db.execute("SELECT id FROM users WHERE role = 'admin' LIMIT 1").fetchone()
    if admin:
        db.execute(
            """
            UPDATE users
            SET institution_type = COALESCE(NULLIF(institution_type, ''), 'other_institution'),
                institution_name = COALESCE(NULLIF(institution_name, ''), 'System Administration')
            WHERE role = 'admin'
            """
        )
        return

    db.execute(
        """
        INSERT INTO users (
            role, institution_type, institution_name, class_roll_number, full_name, father_name, branch, semester, year, dob,
            mobile_number, gmail, email, password_hash, is_mobile_verified
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            "admin",
            "other_institution",
            "System Administration",
            "",
            "System Admin",
            "",
            "Administration",
            "",
            str(date.today().year),
            "",
            "9999999999",
            "admin@gmail.com",
            "admin@example.com",
            generate_password_hash("admin123"),
            1,
        ),
    )


def init_app(app):
    app.teardown_appcontext(close_db)
    with app.app_context():
        init_db()
